# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

os:
  - linux
  - osx

r:
  - oldrel
  - release
  - devel
