---
title: "Untitled"
author: "Derek Corcoran"
date: "January 5, 2016"
output: html_document
---
```{r, message=FALSE, warning=FALSE, echo=FALSE,results='hide'}
#first load libraries
library(raster)
library(maps)
library(maptools)
library(rgdal)
library(dplyr)
library(knitr)
library(unmarked)
library(lubridate)
library(MuMIn)
library(ggplot2)
library(RCurl)
library(foreign)
library(caret)
library(dismo)
library(vegan)
```

###Myyu

```{r,echo=FALSE, warning=FALSE,message=FALSE}
sampling.cov2 <- read.csv("~/new_bats/Rnew_bats/Bats_data_products/sampling.cov2.csv")
sampling.cov2<- sampling.cov2[,-1]
sampling.cov2<- data.frame(sampling.cov2)
preprocov <-preProcess(sampling.cov2[,1:8], method = c("center","scale"))
sampling.cov2<-predict(preprocov, sampling.cov2[,1:8])

Dailycov3 <- read.csv("~/new_bats/Rnew_bats/Bats_data_products/Dailycov3.csv")
Dailycov3 <- Dailycov3 [,-1]


preproDaily <-preProcess(Dailycov3[,], method = c("knnImpute"))
Dailycov3<-predict(preproDaily, Dailycov3)

Julian<-Dailycov3[,1:3]
Max.hum<-Dailycov3[,4:6]
Max.temp<-Dailycov3[,7:9]
Mean.hum<-Dailycov3[,10:12]
Mean.temp<-Dailycov3[,13:15]
Min.hum<-Dailycov3[,16:18]
Min.temp<-Dailycov3[,19:21]
Sd.hum<-Dailycov3[,22:24]
Sd.temp<-Dailycov3[,25:27]

Dailycov3<- list(Julian,Max.hum, Max.temp, Mean.hum,Mean.temp, Min.hum, Min.temp, Sd.hum, Sd.temp)
names(Dailycov3) <- c("Julian", "Maxhum","Maxtemp","Meanhum", "Meantemp","Minhum","Mintemp","sdhum","sdtemp")
```

```{r, echo=FALSE}
#then add the data
RESULTS <- read.csv("~/new_bats/Rnew_bats/Bats_data_products/RESULTS.csv")
RESULTS <- RESULTS[,-1]
RESULTS$START.DATE<- dmy(as.character(RESULTS$START.DATE), tz = "America/Los_Angeles")
RESULTS$END.DATE<- dmy(as.character(RESULTS$END.DATE), tz = "America/Los_Angeles")
```

```{r,echo=FALSE, warning=FALSE,message=FALSE}
BatOccu <- read.csv("~/new_bats/Rnew_bats/BatOccu.csv")
#print(BatOccu)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
#N=49a
BatOccuMyYu<-BatOccu[,2:4]

SimOccuMyYu2<-unmarkedFrameOccu(y = BatOccuMyYu, siteCovs =sampling.cov2, obsCovs=Dailycov3)

model.Occu1.My.Yu2 <- occuRN(~ Julian + Meanhum + Meantemp + sdhum + sdtemp ~  Burn.intensity.soil + I(Burn.intensity.soil^2) + Burn.intensity.Canopy + I(Burn.intensity.Canopy^2) + Burn.intensity.basal + I(Burn.intensity.basal^2),SimOccuMyYu2)

#select.My.Yu2 <- dredge(model.Occu1.My.Yu2, rank = "AICc")

#best2.My.Yu2<-get.models(select.My.Yu2, 1)[[1]]

divmyyu<-predict(model.Occu1.My.Yu2 , type = "state", newdata=sampling.cov2)$Predicted
```


```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, results='hide'}
#N=49
BatOccuMyCa<-BatOccu[,5:7]
```

###Myca

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
#N=49

SimOccuMyCa2<-unmarkedFrameOccu(y = BatOccuMyCa, siteCovs =sampling.cov2, obsCovs=Dailycov3)

model.Occu1.My.Ca2 <- occuRN(~ Julian +  Meanhum + Meantemp + sdhum + sdtemp ~ Burn.intensity.soil + I(Burn.intensity.soil^2) + Burn.intensity.Canopy + I(Burn.intensity.Canopy^2) + Burn.intensity.basal + I(Burn.intensity.basal^2), SimOccuMyCa2)

#select.My.Ca2 <- dredge(model.Occu1.My.Ca2, rank = "AICc")

#best2.My.Ca2<-get.models(select.My.Ca2, 1)[[1]]
#Occu1.layer.MyCa2 <- predict(best2.My.Ca2, type = "state", newdata=Predictors)

#Occu1.layer.MyCa2<-Occu1.layer.MyCa2*PNF
#plot(Occu1.layer.MyCa2$layer.1, colNA="black", main="Occupancy estimation for California Bat",breaks=brks, col=cols,lab.breaks=brks, zlim=c(0,1))

model.Occu1.My.Ca2 

divmyca<-predict(model.Occu1.My.Ca2 , type = "state", newdata=sampling.cov2)$Predicted
```


###MYCY
```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, results='hide'}
#N=49
BatOccuMyCi<-BatOccu[,8:10]

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
#N=49
SimOccuMyCi2<-unmarkedFrameOccu(y = BatOccuMyCi, siteCovs =sampling.cov2, obsCovs=Dailycov3)

model.Occu1.My.Ci2 <- occuRN(~ Julian+ Meanhum + Meantemp + sdhum + sdtemp ~ Burn.intensity.soil + I(Burn.intensity.soil^2) + Burn.intensity.Canopy + I(Burn.intensity.Canopy^2) + Burn.intensity.basal + I(Burn.intensity.basal^2), SimOccuMyCi2)
divmyci<-predict(model.Occu1.My.Ci2 , type = "state", newdata=sampling.cov2)$Predicted
```

###Myvo

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, results='hide'}
#N=49

BatOccuMyVo<-BatOccu[,11:13]
```


```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
#N=49
SimOccuMyVo2<-unmarkedFrameOccu(y = BatOccuMyVo, siteCovs =sampling.cov2, obsCovs=Dailycov3)

model.Occu1.My.Vo2 <- occuRN(~ Julian + Meanhum + Meantemp ~  Burn.intensity.soil  + Burn.intensity.Canopy + Burn.intensity.basal,SimOccuMyVo2)
divmyvo<-predict(model.Occu1.My.Vo2 , type = "state", newdata=sampling.cov2)$Predicted
```

###Myvo

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, results='hide'}
#N=49
BatOccuMyLu<-BatOccu[,14:16]

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
SimOccuMyLu2<-unmarkedFrameOccu(y = BatOccuMyLu, siteCovs =sampling.cov2, obsCovs=Dailycov3)

model.Occu1.My.Lu2 <- occuRN(~ Julian + Meanhum + Meantemp + sdhum + sdtemp ~ Burn.intensity.soil + I(Burn.intensity.soil^2) + Burn.intensity.Canopy + I(Burn.intensity.Canopy^2) + Burn.intensity.basal +I(Burn.intensity.basal^2), SimOccuMyLu2)
divmylu<-predict(model.Occu1.My.Lu2 , type = "state", newdata=sampling.cov2)$Predicted
```

##Western Red Bat (*Lasiurus blossevillii*)


```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, results='hide'}
#N=49
BatOccuLaBl<-BatOccu[,20:22]
```


```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
#N=49

SimOccuLaBl2<-unmarkedFrameOccu(y = BatOccuLaBl, siteCovs =sampling.cov2, obsCovs=Dailycov3)

model.Occu1.La.Bl2 <- occuRN(~ Julian + Meanhum + Meantemp + sdhum + sdtemp ~ Burn.intensity.soil + I(Burn.intensity.soil^2) + Burn.intensity.Canopy + I(Burn.intensity.Canopy^2) + Burn.intensity.basal + I(Burn.intensity.basal^2) ,SimOccuLaBl2)
divlabl<-predict(model.Occu1.La.Bl2 , type = "state", newdata=sampling.cov2)$Predicted
```

#Diversity


```{r, echo=TRUE}
class(divmyca)
div<-cbind(divmyca, divmyyu, divmyci, divmyvo, divmylu, divlabl)
class(div)
kable(div)
h<-diversity(div)
kable(BatOccu)
plot(h)

specnumber(div)
```


#Paquete

```{r, echo=TRUE}
BatOccu<-BatOccu[,-1]
kable(BatOccu)

diversityoccu<- function(pres, sitecov, obscov, spp, form) {
  
  secuencia <- c(1:spp)*(ncol(pres)/spp)
  secuencia2<-secuencia-(secuencia[1]-1)
  
  models <- list()
  div <- list()
  
  for(i in 1:length(secuencia))
  {
    models[[i]] <-c(secuencia2[i]:secuencia[i])
    models[[i]] <- pres[,models[[i]]]
    models[[i]] <- unmarkedFrameOccu(y = models[[i]], siteCovs =sitecov, obsCovs=obscov)
    models[[i]] <- occuRN(form, models[[i]])
    div[[i]] <- predict(models[[i]], type = "state", newdata=sitecov)$Predicted
    div<- as.data.frame(div)
    h<- diversity(div)
  }
  
  result <- list(models=models,Diversity=h)
  return(result)
}

```


```{r, echo=TRUE, cache=TRUE}
a<-diversityoccu(pres = BatOccu, sitecov = sampling.cov2, obscov = Dailycov3, form = ~ Julian + Meanhum + Meantemp + sdhum + sdtemp ~  Burn.intensity.soil + I(Burn.intensity.soil^2) + Burn.intensity.Canopy + I(Burn.intensity.Canopy^2) + Burn.intensity.basal + I(Burn.intensity.basal^2), spp = 17)$Diversity

plot(a)
hist(a)
```